### ISSUE TITLE
'LoadUri' method on virtual renderer should load metaData when possible

### ISSUE THREAD

**Issue by ChriD** [ChriD/RaumkernelLib#2]
the loadUri method on the virtual media renderer works nice but maybe should load the metaData of for example a radio link

**Comment by ChriD** [comment]
The metadata link should be available in the header of the url?!
I have to check this.

**Comment by ChriD** [comment]
eg. response return from icecast when callinf the webradio

```
Status: HTTP/1.0 200 OK
Content-Type:   audio/mpeg
icy-br: 128
ice-audio-info: ice-samplerate=44100;ice-bitrate=128;ice-channels=2
icy-br: 128
icy-description:    ROCK ANTENNE Heavy Metal
icy-genre:  Rock
icy-name:   ROCK ANTENNE Heavy Metal
icy-pub:    1
icy-url:    http://heavymetal.rockantenne.de/heavymetal 
Server: Icecast 2.3.2-kh31
Cache-Control:  no-cache
Expires:    Mon, 26 Jul 1997 05:00:00 GMT
Pragma: no-cache
```

if there would be metadata there would be a header key with
`Icy-MetaData: [linktoMeta]`

**The meta information is also embedded in the audio stream. To read this would be the best solution but this is handled by the raumfeld system :-(**

Well i coud implement the streaming from the url in the kernel and check for metadata and then set it (metadata streaming), but is it worth it?

**Comment by ChriD** [comment]
I'll close this issue. It would be too much effort for the results

**Comment by holli73** [comment]
hello,

so there is no quick win just to pass on a parameter (url) to a png for the station icon?
further is there any way how i can save a loadeduri to the available station buttons?
i can not save loaduri to the station buttons on the rf device - any idea how this could be possible?

thanks
holli
